### Numpy 

Numpy is a fundamental library for advanced data analytics and data manipulation.

In [ ]:
import numpy as np

In [ ]:
import numpy as np
# create array using numpy
# create a simple 1D array

arr = np.array([1,2,3,4,5])
# type(arr) # numpy.ndarray
# arr.shape (5,)
# arr1 = arr.reshape(1, 5) # this will turn the array into an two dimensional array.
# arr1

# arr2 = arr.reshape(2,5) # this will throw an ValueError as the size of the array is not even.
# arr2

In [ ]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
print(arr2.shape) # this is a 2d array

In [ ]:
# numpy functions to create arrays.
np.arange(0,10).reshape(5,2)
np.arange(0,20).reshape(5, 4)

In [ ]:
np.ones((3,4))
np.zeros((3,4))

In [ ]:
# Numpy array properties.
array =np.array([[1,2,3], [4,5,6], [7,8,9]])

print(f"array: ", array)
print(f"array size: ", array.size)
print(f"array dimension: ", array.ndim)
print(f"array datatype: ", array.dtype)
print(f"array shape: ", array.shape)
print(f"array reshape to 1 dimensional array: ", array.reshape(1, 9))
print(f"flattened array: ", array.flatten)

In [ ]:
# vectorized operations.
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(f"addition: ", arr1+arr2)
print(f"substraction: ", arr1 - arr2)
print(f"multiplication: ", arr1 * arr2)
print(f"division: ", arr1 / arr2)

# scaler operations
print(arr1 * 2)  # scaler operations.

In [ ]:
# Universal functions
arr = np.array([1,2,3,4,5])

# square root of each elements.
print(np.sqrt(arr))

# exponential of each elements.
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))

In [ ]:
# Universal functions (ufuncs)
# array slicing and indexing

array = np.array([[1,2,3], [4,5,6], [7,8,9]])

print("array: ", array)
array[0][1] # numpy array indexing is same as list indexing in python.
array[1:] # array slicing
array[2:]

In [ ]:
# need 2,3 and 5,6 from first and second row
array[0:2, 1:]

# need first value of each row from every column.
array[0:, 0]

# need the value of each row.
array[0:, 1]
# need every value from the middle value to the last value.
array[0:, 1:]

# need last columns last row value.
array[2, -1] # back tracking
array[2, 2]


In [ ]:
# modifying values inside array
array[0, 0] = 100 # changing the 0th column 0th index value.
# print(array)

array[1:, 2] = 120 # changing last two columns last value into 120.
array

In [ ]:
# statistical concepts - normalization.
# to have amean of 0 and standard deviation of 1.

data = np.arange(0,10,2)

# mean 
mean = np.mean(data)

# std_dev
std_dev = np.std(data)

# variance
variance = np.var(data)

# median
median = np.median(data)

normalized_data = (data - mean) / std_dev
print(f"normalized data: ", normalized_data)
print(mean, std_dev, variance, median)

In [ ]:
# logical operations using numpy.
data = np.arange(1, 11)

data_filter = data[(data > 5) & (data <= 8)]
data_filter

## this type of data filtering we gonna be doing a lot in pandas series.


In [ ]:
# array Transpose
# array = np.random.random((2,3))

array = np.arange(0,12)
array

reshaped = array.reshape(4,3) # 4 row, 3 columns
reshaped

Transpose = reshaped.T
print(Transpose)

flatten = Transpose.flatten

In [ ]:
# numpy data structures.
array =np.random.randint(1, 11, (2,5))
array

In [ ]:
reshaped_array = array.reshape(5, 2)
Transpose_array = reshaped_array.T

## phase 2

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(1,11)
print("array: ", arr)
print("with step: ", arr[1:8:2])
print("negative indexing: ", arr[-3])

In [ ]:
# specific array slicing and indexing.

arr =np.arange(1,10)
arr2 = arr.reshape(3,3)
# arr2.ndim # 2D array.
print("specific element: ", arr2[1, 2])
print("entire row: ", arr2[2])
print("entire column: ", arr2[:, 1]) # column wise data access.

In [ ]:
unsorted_arr= np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("sorted array: ", np.sort(unsorted_arr))

arr_2d = np.array([[3,1], [1,2], [2,3]])
print("sorted 2D array by column: ", np.sort(arr_2d, axis=0))

In [ ]:
# filtering.
numbers = np.arange(1,11)
# filtered_numbers = numbers[numbers % 2 == 0]
filtered_numbers = numbers[numbers < 5]
filtered_numbers

In [ ]:
# filtering with masking
numbers = np.arange(1,10)
mask = numbers > 5
filtered_numbers = numbers[mask]
filtered_numbers

In [ ]:
# Fancy indexing vs np.where()

indices = [0, 2, 4] # [1, 2, 3, 4, 5, 6, 7, 8, 9]
# print(numbers[indices])

# where_result = np.where(numbers > 5)
# # print(where_result)
# print('NP where : ', numbers[where_result])

where_result = np.where(numbers > 5)
print(numbers[where_result])

In [ ]:
# conditional array.
condition_array = np.where(numbers > 5, 'True', 'False')
condition_array

In [ ]:
# adding and removing data
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print("compatibility shapes", a.shape == b.shape)

In [ ]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
# print(original)
# print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)

In [ ]:
# create a tuple
# tuples are immutable in nature, allow duplicates.
new_tuple = (1,2,3,4,5)
print(new_tuple)

new_tuple.index(3)
new_tuple.count(2)

# accessing tuple elements.
new_tuple[1]

new_tuple[1:4]

In [ ]:
# create a set.
new_set = {1,2,3,4,5, 5}
another_set = {1,2,3,4,5,6,7,8,9}
# print(new_set)

# modifying set.
new_set.add('soham')
new_set

new_set.remove(3)
new_set

difference = new_set.difference(another_set)
difference # returns unique element from the first set.

union = new_set.union(another_set)
union # unionize every elements from both sets.

symmetric_difference = new_set.symmetric_difference(another_set)
symmetric_difference # returns unique elements from both sets.

intersect = new_set.intersection(another_set)
intersect # returns only common elements from both set.



In [ ]:
import numpy as np

# creating tensors and accessing elements inside tensors.
arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
# print(arr.shape)
# print(arr)

# accessing array elements.
arr[1][:, 1]
arr[0][0][1]
arr[0, :]
arr[0][:, 0]
flatten_array = arr.flatten() # flatten function will always flatten the array to ground level.
flatten_array

In [ ]:
# doing operations inside tensors.

arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])
# second_arr = np.array([[[1,2,3]]])
# array broadcasting.
# second_arr = np.array([[1,2,3], [4,5,6], [7,8,9]]) this will throw an error as the dimensions of the second array doesn't matched with first one.

# just because the dimensions matched , the calculation happened.
arr += second_arr
arr

In [ ]:
# array sorting.
arr = np.array([[[3,2,1], [6,4,5]], [[9,7,8], [12, 10 ,11]]])

sorted_arr = np.sort(arr)
sorted_arr

In [ ]:
array = np.array([[3, 1], [1,2], [2,3]])

# in pandas and numpy, axis = 0 means column wise, while axis = 1 mean row wise calculation or sorting.
print(np.sort(array, axis = 0))

In [ ]:
# filtering

array = np.array([1,2,3,4,5])

filtered_arr = array[array > 3] # normal filtering.
mask = array > 3 # mask filtering.
where_filter = np.where(array > 3) # np.where() function.
# array[where_filter]

# running conditional where function because where takes two parameters, one array and boolean conditions.
condition_array = np.where(array > 3, array -1, array)
array[condition_array]

In [ ]:
# array manipulations
# vstack and hstack.
# for stacking array sizes and dimensions matters.
arr1 = np.array([1,2,3,4,5])
# arr2 = np.array([1,2,3]) # this returning a ValueError as the second array size is not equals to the first array.
arr2 = np.array([6,7,8,9,10])

# vstack or vertically stacked. (row-wise operation)
with_new_row = np.vstack((arr1, arr2))
# with_new_row

# hstack or horizontally stacked. (column-wise operation)
with_new_column = np.hstack((arr1, arr2))
# with_new_column

# 2D array operations (vstack and hstack)
arr3 = np.array([[1,2,3], [4,5,6]])
# arr4 = np.array([10, 20, 30]) # since the dimensions didn't match, it is returning a ValueError.

arr4 = np.array([[10, 20, 30]])
with_new_row = np.vstack((arr3, arr4))
with_new_row # vertically added the row.

# important : for hstack the dimension needs to match in terms of 2D array.

arr5 = np.array([[10, 20, 30], [40, 50, 60]])
with_new_col = np.hstack((arr3, arr5))
with_new_col # will return an error because the size of the array doesn't match.


In [ ]:
# element deletion from array.
array = np.array([1,2,3,4,5])

# array deleteion returns the whole array after deletion.
deleted = np.delete(array, 2)
print(f"array after deletion: ", deleted)

In [ ]:
list = [1,2,3,4,5]

another_list = list.pop() # returns a the popped element. Generally pops up elements from backwards of the array.

another_list
list


## Exercises using numpy

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [94]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==== Zomato sales analysis ====")
print("\n Sales data dimension : ", sales_data.ndim)
print("\n Sales data shape", sales_data.shape)
print("\n Sample data for the first 3 rows ", sales_data[:3])

==== Zomato sales analysis ====

 Sales data dimension :  2

 Sales data shape (5, 5)

 Sample data for the first 3 rows  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [98]:
# total sales per year.
# print(np.sum(sales_data[:, 1:], axis=0))
yearly_total = np.sum(sales_data[:, 1:], axis=0) # columnar calc.
# print(yearly_total)

# minimum sales per restaurant.
min_sales_rest = np.min(sales_data[:, 1:], axis = 1) # axis = 1 as row wise operation.
min_sales_rest

# maximum sales per restaurant.
max_sales_rest = np.max(sales_data[:, 1:], axis = 1)
max_sales_rest

# maximum sales per year.
# max_sales_year = np.max(sales_data, axis = 0)
max_sales_year = np.max(sales_data[:, 1:], axis = 0)
max_sales_year

# average sales per restaurant.
avg_sales_rest = np.mean(sales_data[:, 1:], axis = 1)
avg_sales_rest

# cumulative sales per restaurant.
cumsum_rest = np.cumsum(sales_data[:, 1:], axis = 1)
cumsum_rest

# cumulative sum per years
cumsum_year = np.cumsum(sales_data[:, 1:], axis = 0)
cumsum_year

array([[ 150000,  180000,  220000,  250000],
       [ 270000,  320000,  380000,  440000],
       [ 470000,  550000,  640000,  740000],
       [ 650000,  760000,  880000, 1010000],
       [ 810000,  945000, 1085000, 1240000]])

In [ ]:
# vector operations. 
# for broadcasting, we need to match the shape of the arrays.
vc1 = np.array([[1,2,3], [4,5,6]])
vc2 = np.array([10, 20, 30])

print(f"vector addition: \n", vc1 + vc2)
print(f"vector substraction: \n", vc1 - vc2)
print(f"vector multiplication: \n", vc1 * vc2)
print(f"Dot product : \n", np.dot(vc1, vc2))

angle = np.arccos(np.dot(vc1, vc2) / (np.linalg.norm(vc1) * np.linalg.norm(vc2)))
print(angle)

vector addition: 
 [[11 22 33]
 [14 25 36]]
vector substraction: 
 [[ -9 -18 -27]
 [ -6 -15 -24]]
vector multiplication: 
 [[ 10  40  90]
 [ 40 100 180]]
Dot product : 
 [140 320]
[1.16773925 0.45892121]


In [110]:
# vectorized operations.
food_type=np.array(["biriyani", "rice", "chowmein", "momo", "pakora"])

vectorize_upper = np.vectorize(str.upper)
print("Vectorized upper: ", vectorize_upper(food_type))

Vectorized upper:  ['BIRIYANI' 'RICE' 'CHOWMEIN' 'MOMO' 'PAKORA']


In [ ]:
# scaler operations.
monthly_avg = sales_data[:, 1:] / 12 # broadcasting.
monthly_avg

array([[12500.        , 15000.        , 18333.33333333, 20833.33333333],
       [10000.        , 11666.66666667, 13333.33333333, 15833.33333333],
       [16666.66666667, 19166.66666667, 21666.66666667, 25000.        ],
       [15000.        , 17500.        , 20000.        , 22500.        ],
       [13333.33333333, 15416.66666667, 17083.33333333, 19166.66666667]])

In [ ]:
# some more exercises!
# np.array([1, 2, 3]) + 10 # scaler operations.

# np.arange(1, 10, 2) 

a = np.array([[1,2,3],
              [4,5,6]])

# b = np.array([10, 20]) # this will return an ValueError because the size doesn't match with the first array (2,2) vs (2,1)
b = np.array([10, 20, 30])
a + b

a[0][2]
a[0:2, 2]


array([3, 6])

In [126]:
a = np.array([10, 20, 30, 40, 50])
a[a > 25]

array([30, 40, 50])

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# a[0:2, 1:]

b = a[:2]
b[0] = 999 # every elements got modified with new element.
b

array([[999, 999, 999],
       [  4,   5,   6]])

In [134]:
sales = np.array([100, 200, 0, 400, 0, 600])

filter = np.where(sales > 0)
refined_sales = sales[filter]
avg = np.mean(refined_sales)
avg

np.float64(325.0)

In [ ]:
scores = np.array([45, 67, 89, 32, 90, 55])

# replace every value lesser than 50 with 50.
# scores = np.where(scores < 50, 50, scores)
# scores

# replace with normal conditions.
# this is boolean level checking.
scores[scores < 50] = 50 # new value assigned.
scores


array([50, 67, 89, 50, 90, 55])

In [138]:
# Get row-wise average / Get subject-wise (column) max
marks = np.array([[80, 90, 70],
                  [60, 50, 40],
                  [90, 95, 85]])

row_wise_avg = np.mean(marks, axis = 1)
row_wise_avg

column_wise_max = np.max(marks, axis = 0)
column_wise_max

array([90, 95, 85])

In [141]:
a = np.array([10, 20, 30, 40])

idx = np.where(a > 20)
a[idx]

array([30, 40])

In [151]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

a[np.where(a > 3)]

array([4, 5, 6])

In [ ]:
a = np.array([10, 20, 30, 40])

a > 20

mask = a > 20 # boolean masking.
a[mask] # accessing values which passes through the boolean mask.
np.where(a > 20) # returns a tuple with N dimensional array.
a[np.where(a > 20)]


array([30, 40])

In [153]:
a = np.array([[10, 20],
              [30, 40],
              [50, 60]])

rows, cols = np.where(a > 25)

rows, cols

(array([1, 1, 2, 2]), array([0, 1, 0, 1]))

In [1]:
import numpy as np

In [ ]:
# Where function in numpy.
np.where()

a = np.array([13, 14, 56, 32, 15])
b = np.array(["adult", "minor"])
res = np.where(a < 18, b[1], b[0])
res

array(['minor', 'minor', 'adult', 'adult', 'minor'], dtype='<U5')

### broadcasting rules.

"""
NumPy Broadcasting — Simple Explanation

Broadcasting is NumPy’s way of allowing arithmetic operations between arrays
of different shapes without manually resizing or copying them.

Core idea:
NumPy tries to "stretch" the smaller array so its shape matches the larger one,
but only when it is logically safe to do so.

Broadcasting rules:
1. NumPy compares array shapes from RIGHT to LEFT.
2. Two dimensions are compatible if:
   - they are equal, OR
   - one of them is 1
3. If a dimension is missing, NumPy treats it as 1.

Important:
- A dimension with size 1 can be repeated to match the other dimension.
- NumPy does NOT actually copy data; it only behaves as if the array is expanded.

Examples:

Example 1:
a.shape = (2, 3)
b.shape = (3,)  → treated as (1, 3)

Result:
b is repeated for each row of a.

Example 2:
a.shape = (3, 1)
b.shape = (3,)  → treated as (1, 3)

Result:
Both arrays expand to shape (3, 3).

When broadcasting fails:
If at any position the dimensions are different AND neither is 1,
NumPy raises a broadcasting error.

Key takeaway:
Broadcasting works when NumPy can expand dimensions of size 1 to make
both arrays compatible for element-wise operations.
"""


In [28]:
# broadcasting rules.
a = np.array([1,2,3,4,5])
b = 5 # singular element broadcasting.
# here b will expand itself to [5,5,5,5,5] because b shape is (1,) which numpy will treat it as (1,1) and a (5,1) which matches the broadcasting rules.
c = np.array([[1,1,1,1,1], 
              [2,2,2,2,2]]) # c shape (2,5) but a is (1, 5) as one dimension is 1, broadcasting will work here.

d = np.array([[[1,1,1,1,1], 
               [2,2,2,2,2]], 
               [[3,3,3,3,3], 
                [4,4,4,4,4]]]) # shape is (2,2,5) and c also has (2,5) which matches the broadcasting rule.

e = np.array([1,2,3]) # shape (3,) but numpy rewrites it as (1,3)

g = np.array([[[1], [2], [3], [4], [5]]])

c + d

array([[[2, 2, 2, 2, 2],
        [4, 4, 4, 4, 4]],

       [[4, 4, 4, 4, 4],
        [6, 6, 6, 6, 6]]])

In [ ]:
# broadcasting problems.
a = np.array([1,2,3]) # shape -> (3,) == (1,3)

b = np.array([10]) # shape -> (1,) == (1,1), the smallest one will be expanded to match the bigger array.

a + b

array([11, 12, 13])

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]]) # shape -> (2,3)

b = np.array([10, 20, 30]) # shape -> (3,) == (1,3)

a + b

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]]) # shape -> (2,3)

b = np.array([[10],
              [20]]) # shape -> (2,1), this will expand to [[10, 10, 10], [20, 20, 20]] as it has a 1.

a+b

array([[11, 12, 13],
       [24, 25, 26]])

In [37]:
a = np.array([[1, 2, 3],
              [4, 5, 6]]) # shape -> (2, 3)

b = np.array([[10, 20]]) # shape -> (1, 2) # as both the dimensions aren't matching and also none of them are 1, this will throw an error.

a + b

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [ ]:
a = np.array([1, 2, 3]) # shape -> (3,) == (1,3) this will expanded vertically.
b = np.array([[10],
              [20],
              [30]]) # shape -> (3, 1), this will expanded horizontally.

a + b

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

b = 5 # scaler operation (line by line)

A * b

array([[ 5, 10],
       [15, 20]])

In [45]:
a = np.ones((2,3,1))
b = np.ones((1, 3, 4))
a 

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [46]:
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [47]:
a + b

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [49]:
print((a+b).shape)

(2, 3, 4)


In [52]:
b = np.zeros((3, 4, 1))
c = np.ones((5, 1, 4))
b + c

ValueError: operands could not be broadcast together with shapes (3,4,1) (5,1,4) 

In [ ]:
#[ [[1], [1], [1], [1]], [[1], [1], [1], [1]], [[1], [1], [1], [1]] ]
# (3, 4, 1) shaped array.

In [ ]:
A = np.ones((2, 3))
B = np.ones((3, 2))

# A shape [[1,2,3], [3,4,5]]
# B shape [[1,2], [1,2], [1,2]]

A + B # will return ValueError because the dimension is complete opposite.

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

#### NUMPY WHERE FUNCTION

In [ ]:
A = np.array([10, 25, 40, 15]) # 1D array.

print(np.where(A > 20)) # returns index as where function returns elements positions or co-ordinations.

(array([1, 2]),)


In [ ]:
A[np.where(A > 20)] # returns indices than indexes of array inside tuples.
# np.where(A > 20) returns indices of the true elements.
# A[..] returns the elements using the indices.

array([25, 40])

In [59]:
# conditional array creation using where().
arr1 = np.array([10, 25, 40, 15])

np.where(arr1 < 20, 20, arr1)


array([20, 25, 40, 20])

In [ ]:
# boolean masking.
arr1 = np.array([10, 25, 40, 15])

arr1[arr1 > 15] # returns values instead of indices as where() function.

array([25, 40])

In [ ]:
A = np.array([[10, 30, 50],
              [5,  25, 60]])

# np.where(A > 25) # indice or position checking. This is a 2D array so the return will be two arrays containing row-wise and column-wise co-ordinations.
# returning output -> (array[0, 0, 1], array[1, 2, 2])
# A[np.where(A > 25)]

b= np.where(A > 25, 1, 0)


array([[0, 1, 1],
       [0, 0, 1]])

In [ ]:
A = np.array([1, 2, 3])

# np.where(A > 10)

# A[np.where(A > 10)]

array([], dtype=int64)

In [71]:
A = np.array([10, 0, 5])

b = np.where(A != 0, 100 / A, 0)
b

C:\Users\Soham Gon\AppData\Local\Temp\ipykernel_12512\2648411737.py:3: RuntimeWarning: divide by zero encountered in divide
  b = np.where(A != 0, 100 / A, 0)


array([10.,  0., 20.])

In [82]:
## bad age details.
age = np.array([16, -90, np.nan, 50, 34, -3, np.nan, 0, 100])

age = np.where(age > 0) & (~np.nan(age))
age

TypeError: 'float' object is not callable